import type { PokedexEntry } from "@/types/pokemon";

export const FEATURED_POKEMON: PokedexEntry[] = [
  {
    id: 25,
    name: "Pikachu",
    slug: "pikachu",
    types: ["electric"],
    generation: 1,
    region: "Kanto",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
  },
  {
    id: 6,
    name: "Charizard",
    slug: "charizard",
    types: ["fire", "flying"],
    generation: 1,
    region: "Kanto",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
  },
  {
    id: 94,
    name: "Gengar",
    slug: "gengar",
    types: ["ghost", "poison"],
    generation: 1,
    region: "Kanto",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
  },
  {
    id: 150,
    name: "Mewtwo",
    slug: "mewtwo",
    types: ["psychic"],
    generation: 1,
    region: "Kanto",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
  },
  {
    id: 197,
    name: "Umbreon",
    slug: "umbreon",
    types: ["dark"],
    generation: 2,
    region: "Johto",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/197.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/197.png",
  },
  {
    id: 384,
    name: "Rayquaza",
    slug: "rayquaza",
    types: ["dragon", "flying"],
    generation: 3,
    region: "Hoenn",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/384.png",
  },
  {
    id: 448,
    name: "Lucario",
    slug: "lucario",
    types: ["fighting", "steel"],
    generation: 4,
    region: "Sinnoh",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/448.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/448.png",
  },
  {
    id: 778,
    name: "Mimikyu",
    slug: "mimikyu-disguised",
    types: ["ghost", "fairy"],
    generation: 7,
    region: "Alola",
    artwork: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/778.png",
    sprite: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/778.png",
  },
];
